name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      style-python: ${{ steps.filter.outputs.style-python }}
      style-c-cpp: ${{ steps.filter.outputs.style-c-cpp }}
      style-shell: ${{ steps.filter.outputs.style-shell }}
      unit-tests: ${{ steps.filter.outputs.unit-tests }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # @v2
        if: ${{ github.event_name == 'push' }}
        with:
          fetch-depth: 0

        # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            style-python:
              - '.github/**/*'
              - '**/*.py'
              - 'pyproject.toml'
            style-c-cpp:
              - '.github/**/*'
              - '**/*.c'
              - '**/*.h'
              - '**/*.cpp'
              - '**/*.hpp'
            style-shell:
              - '.github/**/*'
              - '**/*.sh'

  style-python:
    needs: changes
    if: ${{ needs.changes.outputs.style-python == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Status Check
        run: echo "Need to check formatting for C/C++!"

  style-c-cpp:
    needs: changes
    if: ${{ needs.changes.outputs.style-c-cpp == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Status Check
        run: echo "Need to check formatting for Python!"

  style-shell:
    needs: changes
    if: ${{ needs.changes.outputs.style-c-cpp == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Status Check
        run: echo "Need to check formatting for POSIX shell!"

  all:
    needs:
     - changes
     - style-python
     - style-c-cpp
     - style-shell
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Status summary
      run: |
        if ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}; then
          echo "One or more required jobs failed or were cancelled"
          exit 1
        else
          echo "All jobs completed successfully"
        fi
